config/routes.rb
HandsomeTest::Application.routes.draw do

  devise_for :users
  resources :hotels do
    resources :ratings, :comments
  end

   root 'hotels#index'
   
   get 'all' => 'hotels#all'
   get '/fonts/:name(.:format)', to: redirect('/assets/%{name}.%{format}')

end

app/models/address.rb
class Address
  include Mongoid::Document

  field :country, type: String
  field :state, type: String
  field :city, type: String
  field :street, type: String

  embedded_in :hotel, :inverse_of => :address
  validates :country, :presence => true
  validates :state, :presence => true
  validates :city, :presence => true
  validates :street, :presence => true
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  field :comment, type: String
  field :user_id, type: BSON::ObjectId
  
  validates :comment, presence: true, length: {minimum: 3, maximum: 160}
  validates :user_id, presence: true
  embedded_in :hotel
  def user
  	user = User.find(self.user_id)
  	user.email
  end
end

app/models/hotel.rb
class Hotel
  include Mongoid::Document
  field :title, type: String
  field :star_rating, type: Integer
  field :breakfast_included, type: Mongoid::Boolean
  field :room_description, type: String
  field :photo, type: String
  field :price_for_room, type: Float
  
  mount_uploader :photo, ImageUploader
  
  embeds_one :address
  has_many :ratings
  embeds_many :comments
  
  validates_presence_of :title
  validates :star_rating, presence: true, numericality: { gteater_than: 0, less_than_or_equal_to: 5}
  validates_associated :address
  validates_presence_of :photo
  validate :photo_size_validation
  accepts_nested_attributes_for :address
  
  # масив рейтингів
  def rates
     entries = Rating.where(:hotel_id => self.id).entries
     entries.map{|rating| rating.rate}  unless entries.nil?
  end
  # визначає середній рейтинг
  def average_rate
    (rates.empty?) ? 0 : (rates.inject(:+).to_f / rates.size)
  end
  # вибирає найкращі N готелів
  def self.top(number)
    Hotel.all.sort_by{|obj|obj.average_rate}.last(number).reverse
  end
  validate :photo_size_validation
 
  private
 
  def photo_size_validation
    errors[:photo] << "should be less than 2MB" if photo.size > 2.megabytes
  end
end

app/models/rating.rb
class Rating
  include Mongoid::Document
  field :rate, :type => Integer
  field :user_id, :type => BSON::ObjectId
  
  belongs_to :hotel
  validates_presence_of :rate
  validates_numericality_of :rate, :greater_than => 0, :less_than_or_equal_to => 5
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
  
  # готелі, оцінені користувачем
  def ratings
    Rating.where(:user_id => self.id).entries
  end
  #Перевіряє чи юзер оцінював готель
  def rated_hotel?(hotel_id)
    if(r = ratings)
      r.each do |rating|
        return rating if rating.hotel_id == hotel_id
      end
    end
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_hotel
  
  # GET /hotels/:id/comments/new
  def new
    @comment = Comment.new
  end

  # POST /hotels/:id/comments
  def create
    comment = comment_params["comment"]
    user_id = current_user.id
    p "comment: #{comment} user_id: #{user_id}"

    @comment = Comment.new(comment: comment, user_id: user_id)
    @hotel.comments << @comment

    respond_to do |format|
      if @comment.valid? and @hotel.comments.last == @comment
         flash[:success] =  'Comment was successfully added'
      else
         flash[:error] =  'Comment was incorrect'
      end
      format.html { redirect_to @hotel }
    end
  end
  private
  def set_hotel
    @hotel = Hotel.find(params[:hotel_id])

  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.top(5)
  end
  def all
    @hotels = Hotel.all
    render "index"
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
    rating = current_user.rated_hotel? @hotel.id
    @comment = Comment.new
     # якщо користувач уже оцінив готель
    if(rating)
      # виводимо поточний рейтинг
      @rating = rating
    else
      # створюємо новий і передаємо у форму
      @rating = Rating.new(:user_id => current_user.id)
    end 
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
    @hotel.address = Address.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render action: 'show', status: :created, location: @hotel }
      else
        format.html { render action: 'new' }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1
  # PATCH/PUT /hotels/1.json
  def update
    respond_to do |format|
      p hotel_params
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def hotel_params
      params.require(:hotel).permit(:title, :star_rating, :breakfast_included,
          :room_description, :photo, :price_for_room, :address_attributes => [:id, :country, :state, :city, :street])
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_hotel, :only => [:index, :create]
  def index
  end
  def create
    rating = Rating.new(:user_id => current_user.id, :rate => ratings_params[:rate])
    @hotel.ratings << rating
    respond_to do |format|
      format.html { redirect_to @hotel, :notice => 'Hotel rating was successfully added.' }
    end
  end
   private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:hotel_id])
    end
    def ratings_params
      params.require(:rating).permit(:rate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-danger"
      when :alert
        "alert-block"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/comments/_index.html.erb
    <% @hotel.comments.each do |comment| %>
      <div class="comment">
        <span class="col-md-3"><%= comment.user %></span>
        <span class="col-md-9"><%= comment.comment %></span>
      </div>
    <% end %>

app/views/comments/_new.html.erb
<%= simple_form_for([@hotel, @comment], html: {class: 'form-vertical'}) do |f| %>
  <div class="form-inputs">
    <%= f.input :comment,label: false, placeholder: 'Leave your comment', :as => :text %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/hotels/_form.html.erb
<%= simple_form_for(@hotel, html: {multipart: true, class: 'form-horizontal'}) do |f| %>
 
<%= render 'shared/error_messages', :target => @hotel %>

  <div class="form-inputs">
    <%= f.input :title, input_html: {class: 'form-control'} %>
  </div>
  <div class="form-inputs">
    <%= f.select(:star_rating, (1..5).to_a, input_html: {class: 'form-control'}) %>
  </div>
  <div class="form-inputs">
    <%= f.label :breakfast_included %>
    <%= f.check_box :breakfast_included, input_html: {class: 'controls form-inline'} %>
  </div>
  <div class="form-inputs">
    <%= f.input :room_description, input_html: {class: 'form-control'} %>
  </div>
  <div class="form-inputs">
    <%= f.label :photo %>
    <%= f.file_field :photo, input_html: {class: 'form-control'} %>
  </div>
  <div class="form-inputs">
    <%= f.input :price_for_room, input_html: {class: 'form-control'} %>
  </div>
    <%= f.simple_fields_for :address do |builder| %>
	<div class="form-inputs">
	<%= builder.input :country, :as => :string, input_html: {class: 'form-control'} %>
	</div>
	<div class="form-inputs">
        <%= builder.input :state, input_html: {class: 'form-control'} %>
        </div>
	<div class="form-inputs">
        <%= builder.input :city, input_html: {class: 'form-control'} %>
        </div>
	<div class="form-inputs">
        <%= builder.input :street, input_html: {class: 'form-control'} %>
        </div>
    <% end %>
  <div class="actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/hotels/edit.html.erb
<h1>Editing hotel</h1>

<%= render 'form' %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

app/views/hotels/index.html.erb
 
<div class="hotels">
  <% @hotels.each do |hotel| %>
  <div class="col-lg-4">
    <%= link_to image_tag(hotel.photo_url(:thumb), class: 'img-circle add-hotel', alt: hotel.title), hotel %>
    <h3><%= hotel.title %></h3>
    <h4 class="glyphicon glyphicon-thumbs-up"><%= hotel.average_rate %></h4>
  </div><!-- /.col-lg-4 -->
  <% end %>
  <div class="col-lg-4">
  	<%= link_to(content_tag(:div, content_tag(:span, "", class: "glyphicon glyphicon-plus hotel-plus"),:class => "img-circle add-hotel"), new_hotel_path, id: 'add-hotel') %>
  	<h3>Добавити готель</h3>
  </div>
</div><!-- /.row -->

app/views/hotels/new.html.erb
<div class="hotel">
<h1>New hotel</h1>

<%= render 'form' %>

<%= link_to 'Back', hotels_path, class: 'btn btn-link' %>
</div>

app/views/hotels/show.html.erb
<div class="hotel">


<div class="col-md-4">
 <%= image_tag @hotel.photo_url(:thumb), class: 'img-circle' %>
 <div>
   <%= render partial: 'ratings/new', :object => [@hotel, @rating] %>
 </div>
</div>
<div class="col-md-8">
  <h2><%= @hotel.title %></h2>

  <!-- /div -->
  <p>
    <strong>Price for room:</strong>
    <%= @hotel.price_for_room %>
  </p>
<p>
  <strong>Star rating:</strong>
  <%= @hotel.star_rating %>
</p>

<p>
  <strong>breakfast included:</strong>
  <%= @hotel.breakfast_included %>
</p>

<p>
  <strong>Room description:</strong>
  <%= @hotel.room_description %>
</p>
  <p>
    <strong>Country:</strong>
    <%= @hotel.address.country %>
  </p>

  <p>
    <strong>State:</strong>
    <%= @hotel.address.state %>
  </p>

  <p>
    <strong>City:</strong>
    <%= @hotel.address.city %>
  </p>

  <p>
    <strong>Street:</strong>
    <%= @hotel.address.street %>
  </p>
</div>


<div class="comments">
  <%= render partial: 'comments/new', :object => [@hotel, @comment]  %>
  <%= render partial: 'comments/index', :object => @hotel %>
</div>

<%= link_to 'Back', hotels_path, class: 'btn btn-link' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HandsomeTest</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <!--[if lt IE 7]>
              <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
          <![endif]-->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Hotel Advisor', hotels_path, :class => 'navbar-brand' %>
        </div>
         <div class="navbar pull-right">
          <% if current_user %>
            Logged as: <%= current_user.email %> |
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-link" %>
          <% else %>
            <%= link_to "sign in", new_user_session_path %>
          <% end %>
        </div>
      </div>
    </div>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <%= render partial: "shared/flash_messages", flash: flash %> 
        <%= yield %>
      </div>
      
    </div>
  </body>
</html>

app/views/ratings/_new.html.erb
  <%= simple_form_for([@hotel, @rating]) do |f|%>
    <% if @rating.rate %>
      <h3>Ваша оцінка: <%= @rating.rate %></h3>
    <% else %>
    	<h3>Оцініть готель: </h3>
      <%= f.select(:rate, (1..5).to_a) %>
      <%= f.button :submit,value: 'Rate', class: 'btn btn-success' %>
    <% end %>
  <% end %>

app/views/shared/_error_messages.html.erb
 <% if target.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% target.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/shared/_flash_ messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>